worker_processes auto;
events { worker_connections 768; }
http {
    server {
        listen 80;
        server_name j13a602.p.ssafy.io;

        # Let's Encrypt 인증 요청을 처리하기 위한 경로
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # 인증 외의 다른 모든 요청은 404 반환
        location / {
            return 404;
        }
    }
}
