worker_processes auto;

events {
    worker_connections 768; 
}

http {
    client_max_body_size 15M;

    upstream blue_server {
        server spring-app-blue:8081;
    }

    upstream green_server {
        server spring-app-green:8082;
    }

    server {
        listen 80;
        server_name j13a602.p.ssafy.io;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name j13a602.p.ssafy.io;

        ssl_certificate /etc/letsencrypt/live/j13a602.p.ssafy.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/j13a602.p.ssafy.io/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
        
        location / {
            proxy_pass http://blue_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /test/ {
            proxy_pass http://green_server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /fastapi/ {
            proxy_pass http://fastapi-app:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
